[config]
schemaVersion = "0.0.1"

[package]
namespace = "SGG_Modding"
name = "SeerSuite"
versionNumber = "1.0.3"
description = "Defines debug tools such as an Object Browser and Script Console."
websiteUrl = "https://github.com/SGG-Modding/SeerSuite"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.111"
SGG_Modding-ENVY = "1.2.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "libraries", "mods" ]
